server:
  port: 80
  servlet:
    context-path: /
spring:
  datasource:
    username: root
    password: 1178
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/mall?useSSL=false&useUnicode=true&characterEncoding=utf8